enum TokenType {
  INVALID,

  // Delimeters
  INDENT, WHITESPACE, ARBITRARY_TEXT, PLAIN_TEXT, LBRACKET, RBRACKET, LPAREN, RPAREN, SEMI,

  // Symbols
  AMPERSAND, PIPE, COMMENT_START, COMMENT_START_UNBUFFERED,

  // Operators
  ASTERISK, COLON, COMMA, DASH, DOT, EQUALS, PLUS, SLASH, QUESTION,

  // Boolean Operators
  BOOL_AND, BOOL_EQUALS, BOOL_NOT_EQUALS, BOOL_OR,


  // Control flow and keywords
  APPEND, BLOCK, DOCTYPE, EACH, EXTENDS, IF, IN, INCLUDE, ELSE, MIXIN, PREPEND, UNLESS, WHILE,

  // Data
  BOOLEAN,
  NUMBER,
  SINGLE_QUOTED_STRING,
  DOUBLE_QUOTED_STRING,
  TEMPLATE_STRING,
  STRING_INTERPOLATION,
  CLASS_NAME,
  ELEMENT_ID,
  TAG_NAME
}